<?php


namespace App\Tenant;

use Illuminate\Database\Eloquent\Model;

trait TenantModels
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

//        atribui o id do usuário
        static::addGlobalScope(new TenantScope());

//        antes de criar ele já atribui o id do usuário
        static::creating(function (Model $model){
            if (\Tenant::getTenant()){
                $userId = \Tenant::getTenant()->id;
                $model->idusuario = $userId;
            }
        });
    }
}
